language: python
python: 2.7
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=pypy
    - TOXENV=pep8
    - TOXENV=docs

install:
    - "[[ ${TOXENV} == pypy ]] && sudo add-apt-repository -y ppa:pypy/ppa || true"
    - "[[ ${TOXENV} == pypy ]] && sudo apt-get -y update && sudo apt-get -y install pypy || true"
    # This is required because we need to get rid of the Travis installed PyPy
    # or it'll take precedence over the PPA installed one.
    - "[[ ${TOXENV} == pypy ]] && sudo rm -rf /usr/local/pypy/bin || true"
    - pip install tox coveralls

script:
    - tox

after_success:
    - coveralls
